// AUTO-GENERATED by tools/gen-data.mjs from ../../data/*.csv — do not edit by hand.
// Venue ranking + override tables, embedded so the resolver needs no file IO at runtime.
// Loaded as a classic subscript in Zotero (top-level vars share the plugin scope) and
// as a CommonJS module in Node tests (module.exports).
var ZM_RANKINGS = [
  {
    "canonical": "NeurIPS",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "neurips|nips|neural information processing systems|advances in neural information processing systems",
    "write_as": "Advances in Neural Information Processing Systems"
  },
  {
    "canonical": "ICML",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "icml|international conference on machine learning",
    "write_as": "International Conference on Machine Learning"
  },
  {
    "canonical": "ICLR",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "iclr|international conference on learning representations",
    "write_as": "International Conference on Learning Representations"
  },
  {
    "canonical": "CVPR",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "cvpr|computer vision and pattern recognition|ieee/cvf conference on computer vision and pattern recognition",
    "write_as": "IEEE/CVF Conference on Computer Vision and Pattern Recognition"
  },
  {
    "canonical": "ICCV",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "iccv|international conference on computer vision",
    "write_as": "International Conference on Computer Vision"
  },
  {
    "canonical": "ECCV",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "eccv|european conference on computer vision",
    "write_as": "European Conference on Computer Vision"
  },
  {
    "canonical": "AAAI",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "aaai|association for the advancement of artificial intelligence|aaai conference on artificial intelligence",
    "write_as": "AAAI Conference on Artificial Intelligence"
  },
  {
    "canonical": "IJCAI",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "ijcai|international joint conference on artificial intelligence",
    "write_as": "International Joint Conference on Artificial Intelligence"
  },
  {
    "canonical": "ACL",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "annual meeting of the association for computational linguistics|association for computational linguistics",
    "write_as": "Annual Meeting of the Association for Computational Linguistics"
  },
  {
    "canonical": "EMNLP",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "emnlp|empirical methods in natural language processing",
    "write_as": "Conference on Empirical Methods in Natural Language Processing"
  },
  {
    "canonical": "NAACL",
    "kind": "conference",
    "core_tier": "A",
    "aliases": "naacl|north american chapter of the association for computational linguistics|annual conference of the nations of the americas chapter of the association for computational linguistics|conference of the north american chapter of the association for computational linguistics: human language technologies",
    "write_as": "Annual Conference of the Nations of the Americas Chapter of the Association for Computational Linguistics"
  },
  {
    "canonical": "COLT",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "colt|conference on learning theory|computational learning theory",
    "write_as": "Conference on Learning Theory"
  },
  {
    "canonical": "UAI",
    "kind": "conference",
    "core_tier": "A",
    "aliases": "uai|uncertainty in artificial intelligence",
    "write_as": "Conference on Uncertainty in Artificial Intelligence"
  },
  {
    "canonical": "AISTATS",
    "kind": "conference",
    "core_tier": "A",
    "aliases": "aistats|artificial intelligence and statistics",
    "write_as": "International Conference on Artificial Intelligence and Statistics"
  },
  {
    "canonical": "KDD",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "kdd|knowledge discovery and data mining",
    "write_as": "ACM SIGKDD Conference on Knowledge Discovery and Data Mining"
  },
  {
    "canonical": "SIGIR",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "sigir|research and development in information retrieval",
    "write_as": "International ACM SIGIR Conference on Research and Development in Information Retrieval"
  },
  {
    "canonical": "WWW",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "the web conference|world wide web conference|acm web conference",
    "write_as": "ACM Web Conference"
  },
  {
    "canonical": "WACV",
    "kind": "conference",
    "core_tier": "A",
    "aliases": "wacv|winter conference on applications of computer vision",
    "write_as": "IEEE/CVF Winter Conference on Applications of Computer Vision"
  },
  {
    "canonical": "ACM MM",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "acm multimedia|acm international conference on multimedia",
    "write_as": "ACM International Conference on Multimedia"
  },
  {
    "canonical": "ICRA",
    "kind": "conference",
    "core_tier": "A",
    "aliases": "icra|international conference on robotics and automation",
    "write_as": "IEEE International Conference on Robotics and Automation"
  },
  {
    "canonical": "IROS",
    "kind": "conference",
    "core_tier": "A",
    "aliases": "iros|intelligent robots and systems",
    "write_as": "IEEE/RSJ International Conference on Intelligent Robots and Systems"
  },
  {
    "canonical": "SIGGRAPH",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "siggraph|international conference on computer graphics and interactive techniques",
    "write_as": "International Conference on Computer Graphics and Interactive Techniques"
  },
  {
    "canonical": "JMLR",
    "kind": "journal",
    "core_tier": "",
    "aliases": "jmlr|journal of machine learning research",
    "write_as": ""
  },
  {
    "canonical": "TPAMI",
    "kind": "journal",
    "core_tier": "",
    "aliases": "tpami|transactions on pattern analysis and machine intelligence",
    "write_as": ""
  },
  {
    "canonical": "TMLR",
    "kind": "journal",
    "core_tier": "",
    "aliases": "tmlr|transactions on machine learning research",
    "write_as": ""
  },
  {
    "canonical": "TACL",
    "kind": "journal",
    "core_tier": "",
    "aliases": "tacl|transactions of the association for computational linguistics",
    "write_as": ""
  },
  {
    "canonical": "IJCV",
    "kind": "journal",
    "core_tier": "",
    "aliases": "ijcv|international journal of computer vision",
    "write_as": ""
  },
  {
    "canonical": "Nature",
    "kind": "journal",
    "core_tier": "",
    "aliases": "nature",
    "write_as": ""
  },
  {
    "canonical": "Nature Machine Intelligence",
    "kind": "journal",
    "core_tier": "",
    "aliases": "nature machine intelligence",
    "write_as": ""
  },
  {
    "canonical": "Science",
    "kind": "journal",
    "core_tier": "",
    "aliases": "science",
    "write_as": ""
  },
  {
    "canonical": "CACM",
    "kind": "journal",
    "core_tier": "",
    "aliases": "communications of the acm",
    "write_as": ""
  },
  {
    "canonical": "USENIX Security",
    "kind": "conference",
    "core_tier": "A*",
    "aliases": "usenix security",
    "write_as": "USENIX Security Symposium"
  },
  {
    "canonical": "ACM Computing Surveys",
    "kind": "journal",
    "core_tier": "",
    "aliases": "acm computing surveys|csur",
    "write_as": ""
  },
  {
    "canonical": "JASA",
    "kind": "journal",
    "core_tier": "",
    "aliases": "journal of the american statistical association",
    "write_as": ""
  },
  {
    "canonical": "TKDE",
    "kind": "journal",
    "core_tier": "",
    "aliases": "transactions on knowledge and data engineering",
    "write_as": ""
  }
];
var ZM_OVERRIDES = {
  "1406.2661": {
    "canonical": "NeurIPS",
    "year": 2014
  }
};
if (typeof module !== "undefined" && module.exports) {
  module.exports = { RANKINGS: ZM_RANKINGS, OVERRIDES: ZM_OVERRIDES };
}
